# Generated by cask-dotfile-generator
# Created by: @seethroughtrees
# https://github.com/seethroughtrees/brew-cask-dotfile-generator
cask_args appdir: "/Applications"
tap "caskroom/cask"

brew "autoconf"
brew "gdbm"
brew "icu4c"
brew "makedepend"
brew "openssl"
brew "pcre"
brew "pkg-config"
brew "rbenv"
brew "ruby-build"
brew "vim"
brew "wget"
brew "zsh"
brew "antigen"
brew "antigen"

cask "1password"
cask "atom"
cask "google-chrome"
cask "iterm2"
cask "spotify"
cask "whatsapp"
